### ISSUE TITLE
no x-robots-tag in my bladea

### ISSUE THREAD

**Issue by oktu** [spatie/laravel-robots-middleware#15]
I did everything as described in the instructions. But my blades don't contain the x-robots-tag. Shoul I add some code to tamplate.blade?

**Comment by praditha-hidayat** [comment]
yes, so am I.
Nothing change on the header part.

**Comment by sebastiandedeyne** [comment]
Hi @oktu,

That's as expected. This package adds robots tags in the response's HTTP headers, not as `meta` tags in HTML.

@praditha-hidayat if you're experiencing a different issue, please reopen a new issue with some code snippets of your configuration.
