### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by blomdahldaniel** [spatie/laravel-robots-middleware#2]
Hi!

Would love to be able to use yet another of your packages. 
However, it does not seem like I have the right PHP version for this.

**PLEASE WRITE PHP VERSION REQUIREMENT IN THE README!!!**
Have been faced the same disappointment with one of your awesome packages before.
Just write it out so that users dont have to find the error message upon installation!

Is it possible to customize the src easily to match php 5.6?
Or why is a newer version of php required?

**Comment by freekmurze** [comment]
Here's some background on why we required PHP 7: https://murze.be/2016/01/why-we-are-requiring-php-7-for-our-new-packages/

**Comment by blomdahldaniel** [comment]
Thank you for the link. I understand your choice of php version but I still want to suggest/request that you write out the PHP7 requirement in your readme so that people don't have to "magically" know that spatie only creates packages for PHP7.
